[phases.setup]
nixPkgs = ["...", "nodejs_22"]

[phases.install]
dependsOn = ["setup"]
cmds = ["bundle install", "npm install"]

[phases.build]
dependsOn = ["install"]
cmds = ["npm run build"]

[phases.build.env]
DISABLE_DATABASE_ENVIRONMENT_CHECK = "1"

[start]
cmd = "./bin/railway-start-simple"
