[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/"
startCommand = "bundle exec rails db:migrate && bundle exec puma -C config/puma.rb"

[environments.production]
RAILS_ENV = "production"
RAILS_SERVE_STATIC_FILES = "true"
RAILS_LOG_TO_STDOUT = "true"

[environments.production.variables]
# Railway will automatically provide DATABASE_URL and PORT
