[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/"

[environments.production]
RAILS_ENV = "production"
RAILS_SERVE_STATIC_FILES = "true"
RAILS_LOG_TO_STDOUT = "true"

[environments.production.variables]
# Railway will automatically provide DATABASE_URL and PORT
